src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $Nombre = null;

    #[ORM\Column(length: 255)]
    private ?string $telefono = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Hijos::class)]
    private Collection $hijos;

    public function __construct()
    {
        $this->hijos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->telefono;
    }

    public function setTelefono(string $telefono): self
    {
        $this->telefono = $telefono;

        return $this;
    }

    /**
     * @return Collection<int, Hijos>
     */
    public function getHijos(): Collection
    {
        return $this->hijos;
    }

    public function addHijo(Hijos $hijo): self
    {
        if (!$this->hijos->contains($hijo)) {
            $this->hijos->add($hijo);
            $hijo->setUser($this);
        }

        return $this;
    }

    public function removeHijo(Hijos $hijo): self
    {
        if ($this->hijos->removeElement($hijo)) {
            // set the owning side to null (unless already changed)
            if ($hijo->getUser() === $this) {
                $hijo->setUser(null);
            }
        }

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use PHPStan\PhpDocParser\Ast\Type\ArrayTypeNode;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')
            // ->add('roles', ChoiceType::class, [
            //     'multiple' => true,
            //     'choices' => [
            //         'ROLE_ADMIN' => 'ROLE_ADMIN',
            //         'ROLE_USER' => 'ROLE_USER',
            //     ],
            // ])
            // ->add('password') No vamos a cambiar la contraseña. Si la cambias la lias.
            ->add('Nombre')
            ->add('telefono')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Hijos;
use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\Persistence\ManagerRegistry;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/index', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, UserRepository $userRepository): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user->setRoles(['ROLE_USER']);
            $userRepository->save($user, true);

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user, ManagerRegistry $managerRegistry): Response
    {
        $repo = $managerRegistry->getManager()->getRepository(Hijos::class);
        $hijos = $user->getHijos();
        return $this->render('user/show.html.twig', [
            'user' => $user,
            'hijos' => $hijos
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, UserRepository $userRepository,  UrlGeneratorInterface $urlGenerator): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $userRepository->save($user, true);
            // Obtener el ID del usuario actual a traves del propio hijo
            $userId = $user->getId();

            // Generar la URL con el parámetro del ID del usuario
            $url = $urlGenerator->generate('app_user_show', ['id' => $userId]);

            // Redirigir a la URL generada
            return $this->redirect($url);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, UserRepository $userRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $user->getId(), $request->request->get('_token'))) {
            $userRepository->remove($user, true);
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Deseas eliminar a este usuario?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-danger">Borrar</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Registrar') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar usuario{% endblock %}

{% block body %}

    <h1>Editar usuario</h1>

    {{ include('user/_form.html.twig', {'button_label': 'Actualizar'}) }}

    <a class="btn btn-primary" href="{{ path('app_user_index') }}">Volver</a>

    {{ include('user/_delete_form.html.twig') }}
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lista de usuarios{% endblock %}

{% block body %}

    <h1>Lista de usuarios</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Telefono</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.Nombre }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
        
                
                <td>{{ user.telefono }}</td>
                <td>
                    <a class="btn btn-info" href="{{ path('app_user_show', {'id': user.id}) }}">Ver</a>
                    <a class="btn btn-primary" href="{{ path('app_user_edit', {'id': user.id}) }}">Editar</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">No se han encontrado registros</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-success" href="{{ path('app_register') }}">Crear nuevo usuario</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nuevo usuario{% endblock %}

{% block body %}

    <h1>Crear nuevo usuario</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('app_user_index') }}">Volver a la lista</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Usuario{% endblock %}

{% block body %}

    <h1>Usuario</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <!--
            <tr>
                <th>Roles</th>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
            </tr>
            -->
            <!--
            <tr>
                <th>Password</th>
                <td>{{ user.password }}</td>
            </tr>
            -->
            <tr>
                <th>Nombre</th>
                <td>{{ user.Nombre }}</td>
            </tr>
            <tr>
                <th>Telefono</th>
                <td>{{ user.telefono }}</td>
            </tr>
        </tbody>
    </table>
    {% if is_granted('ROLE_ADMIN') %} <!-- No se podrá borrar el usuario por su parte -->
      {{ include('user/_delete_form.html.twig') }}
       <a class="btn btn-primary" href="{{ path('app_user_index') }}">Volver</a>
    {% endif %}

        

    <a class="btn btn-success" href="{{ path('app_user_edit', {'id': user.id}) }}">Editar</a>
    <table class="table"> <!--Tabla para mostrar a los hijos -->
    <h2 >Mis hijos</h2>
    <tr>
        <th>Nombre</th>
        <th>Apellidos</th>
        <th>Fecha Nacimiento</th>
    </tr>
    {% for item in hijos %}
        <tr>
            <td>{{item.nombre}}</td>
            <td>{{item.apellidos}}</td>
            <td>{{item.getFechaNacimiento()|date('d/m/Y')}}</td>
            <td><a class="btn btn-info" href="{{ path('app_hijos_show', {'id': item.id}) }}">Ver</a></td>
            <!-- El hijo no deberia deletearlo el padre.
            <td><a class="btn btn-danger" href="{{ path('app_hijos_delete', {'id': item.id}) }}">Borrar</a></td>
            -->
        </tr>
    {% endfor %}
    </table>
    <!--
    <a class="btn btn-secondary" href="{{ path('app_user_index') }}">back to list</a>

    <a class="btn btn-warning" href="{{ path('app_user_edit', {'id': user.id}) }}">edit</a>
    -->
  
{% endblock %}